# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Anushka Tak
title: Masters in Data Science
email: tak.a@northeastern.edu
linkedin: https://www.linkedin.com/in/anushka-tak/
website: https://anushkatak007.github.io/

# Social links
twitter_username: facespics
github_username:  anushkatak007
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: chillwildlife
linkedin_username: jameswgrant
# pinterest_username: jekyll
youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jfif
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Anushka  and I'm a motivated, meticulous and curious Data Scientist with proven leadership capabilities, who is passionate about statistics and analysis. Proficient in discerning critical business problems, handling data and developing models to generate high value insights. 

  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

